PATCH_PROTOCOL_VERSION = "1.0.2"
ACTION_MODE_GAMEPAD = "gamepad"
ACTION_MODE_MOUSE = "mouse"

MIN_AUDIO_RMS = 0.001
CAST_DELAY_SECONDS = 0.5
START_DELAY_SECONDS = 3.0
GAMEPAD_PRESS_SECONDS = 0.35
GAMEPAD_REFRESH_SECONDS = 0.05
PATCH_PULSE_MARGIN_SECONDS = 0.25
PIPE_CONNECT_TIMEOUT_SECONDS = 5.0
